sudo: false

language: node_js
node_js:
  - stable

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test

branches:
  only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
- sparrow.jang@gmail.com
